<a href="https://colab.research.google.com/github/anmollate/Data-Science/blob/main/Normalization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Normalization

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_csv("https://gist.githubusercontent.com/tijptjik/9408623/raw/b237fa5848349a14a14e5d4107dc7897c21951f5/wine.csv")

In [ ]:
df.head(5)

,Wine,Alcohol,Malic.acid,Ash,Acl,Mg,Phenols,Flavanoids,Nonflavanoid.phenols,Proanth,Color.int,Hue,OD,Proline
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735

In [ ]:
x=df[["Alcohol","Malic.acid"]]

In [ ]:
y=df['Wine']

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

In [ ]:
#now normalizing the values
from sklearn.preprocessing import MinMaxScaler

scaler=MinMaxScaler()

In [ ]:
scaler.fit(x_train)

MinMaxScaler()

In [ ]:
x_train_scaled=scaler.transform(x_train)
x_test_scaled=scaler.transform(x_test)
#outputs in numpy array

In [ ]:
#converting the scaled values to df
x_train_scaled=pd.DataFrame(x_train_scaled,columns=['Alcohol','Malic.acid'])
x_test_scaled=pd.DataFrame(x_test_scaled,columns=['Alcohol','Malic.acid'])

In [ ]:
x_train_scaled

      Alcohol  Malic.acid
0    0.647368    0.549898
1    0.389474    0.171079
2    0.342105    0.020367
3    0.592105    0.152749
4    0.331579    0.395112
..        ...         ...
119  0.744737    0.126273
120  0.321053    0.171079
121  0.881579    0.199593
122  0.436842    0.130346
123  0.344737    0.317719

[124 rows x 2 columns]

In [ ]:
x_train_scaled.describe()

          Alcohol  Malic.acid
count  124.000000  124.000000
mean     0.508765    0.308143
std      0.221444    0.224504
min      0.000000    0.000000
25%      0.331579    0.152749
50%      0.503947    0.205703
75%      0.701316    0.464358
max      1.000000    1.000000

In [ ]:
#training and testing the logistic regression model
from sklearn.linear_model import LogisticRegression
model1=LogisticRegression()
model2=LogisticRegression()

model1.fit(x_train, y_train)
model2.fit(x_train_scaled, y_train)

y_pred=model1.predict(x_test)
y_pred_scaled=model2.predict(x_test_scaled)

from sklearn.metrics import accuracy_score

print("Not scaled accuracy:",accuracy_score(y_test,y_pred))
print("Scaled accuracy:",accuracy_score(y_test,y_pred_scaled))

Not scaled accuracy: 0.7407407407407407
Scaled accuracy: 0.7407407407407407